#!/usr/bin/env bash

rm -rf .libs
rm -rf modules
rm -rf autom4te.cache
rm -rf build
rm -rf include
rm -rf modules

rm -f acinclude.m4
rm -f aclocal.m4
rm -f config.cache
rm -f config.guess
rm -f config.h
rm -f config.h.in
rm -f config.h.in~
rm -f config.log
rm -f config.nice
rm -f config.status
rm -f config.sub
rm -f configure
rm -f configure~
rm -f configure.ac
rm -f configure.in
rm -f install-sh
rm -f libtool
rm -f ltmain.sh
rm -f Makefile
rm -f Makefile.fragments
rm -f Makefile.global
rm -f Makefile.objects
rm -f missing
rm -f mkinstalldirs
rm -f run-tests.php
rm -f tmp-php.ini
rm -f tests/**/*.diff
rm -f tests/**/*.out
rm -f tests/**/*.php
rm -f tests/**/*.exp
rm -f tests/**/*.log
rm -f tests/**/*.sh
rm -f tests/**/*.db
rm -f tests/**/*.mem
rm -f tests/*.diff
rm -f tests/*.out
rm -f tests/*.php
rm -f tests/*.exp
rm -f tests/*.log
rm -f tests/*.sh
rm -f tests/*.db
rm -f tests/*.mem
rm -f ./*.dep
rm -f ./*.la
rm -f ./*.lo
