/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 2a49b0018d08274c6d1f4788dd4ccc3a0e5dd091 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_register_operator_overload, 0, 3, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, class, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO(0, operator, IS_LONG, 0)
	ZEND_ARG_TYPE_INFO(0, callable, IS_CALLABLE, 0)
ZEND_END_ARG_INFO()


ZEND_FUNCTION(register_operator_overload);


static const zend_function_entry ext_functions[] = {
	ZEND_FE(register_operator_overload, arginfo_register_operator_overload)
	ZEND_FE_END
};

static void register_operators_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("OPERATORS_ADD", 1, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_SUB", 2, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_MUL", 3, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_DIV", 4, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_MOD", 5, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_POW", 12, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_SL", 6, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_SR", 7, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_CONCAT", 8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_BW_OR", 9, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_BW_AND", 10, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_BW_XOR", 11, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_IS_IDENTICAL", 16, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_IS_NOT_IDENTICAL", 17, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_IS_EQUAL", 18, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_IS_NOT_EQUAL", 19, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_PRE_INC", 34, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_PRE_DEC", 35, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_POST_INC", 36, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_POST_DEC", 37, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_SPACESHIP", 170, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPERATORS_ASSIGN", 22, CONST_PERSISTENT);
}
