name: Build extension
on:
  # When a new tag is pushed, we can build, and upload the DLLs to it.
  push:
    # branches: ['**'] # Uncomment this to run on push to a branch
    tags: ['*']
  # create: # Uncomment this to run on tag/branch creation
  # pull_request: # Uncomment this to run on pull requests

permissions:
  contents: write

jobs:
  # This job generates a matrix of PHP versions, architectures, and thread safety options
  # This is done by reading the constraints from composer.json or the package.xml file.
  # Please refer to https://github.com/php/php-windows-builder#get-the-job-matrix-to-build-a-php-extension
  get-extension-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.extension-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get the extension matrix
        id: extension-matrix
        uses: php/php-windows-builder/extension-matrix@v1
        with:
          # The Windows extension builder has a bug:
          # ERROR: Worker 2 reported unexpected E_DEPRECATED: explode(): Passing null to parameter #2 ($string) of type string is deprecated in D:\a\php-operators\php-operators\build\3cdf7ed6\run-tests.php on line 3618
          # This code has no `explode` anywhere in it! So, disable testing until they fix it.
          run-tests: false

  # This job builds the extension on Windows using the matrix generated from the previous job.
  build:
    needs: get-extension-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(needs.get-extension-matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build the extension
        uses: php/php-windows-builder/extension@v1
        with:
          # Always specify the php-version, arch, and ts as they are required inputs.
          # Please refer to https://github.com/php/php-windows-builder#build-a-php-extension
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}

  # This job uploads the build artifacts to the immutable GitHub release it creates.
  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Upload artifact to the release
        uses: php/php-windows-builder/release@v1
        with:
          release: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment the line below to create a draft release
          # draft: 'true'